// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc2
// source: proto/game.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameSerivce_Play_FullMethodName = "/battle.GameSerivce/Play"
)

// GameSerivceClient is the client API for GameSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameSerivceClient interface {
	Play(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, ServerResponse], error)
}

type gameSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameSerivceClient(cc grpc.ClientConnInterface) GameSerivceClient {
	return &gameSerivceClient{cc}
}

func (c *gameSerivceClient) Play(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, ServerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameSerivce_ServiceDesc.Streams[0], GameSerivce_Play_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayerAction, ServerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSerivce_PlayClient = grpc.BidiStreamingClient[PlayerAction, ServerResponse]

// GameSerivceServer is the server API for GameSerivce service.
// All implementations must embed UnimplementedGameSerivceServer
// for forward compatibility.
type GameSerivceServer interface {
	Play(grpc.BidiStreamingServer[PlayerAction, ServerResponse]) error
	mustEmbedUnimplementedGameSerivceServer()
}

// UnimplementedGameSerivceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameSerivceServer struct{}

func (UnimplementedGameSerivceServer) Play(grpc.BidiStreamingServer[PlayerAction, ServerResponse]) error {
	return status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedGameSerivceServer) mustEmbedUnimplementedGameSerivceServer() {}
func (UnimplementedGameSerivceServer) testEmbeddedByValue()                     {}

// UnsafeGameSerivceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameSerivceServer will
// result in compilation errors.
type UnsafeGameSerivceServer interface {
	mustEmbedUnimplementedGameSerivceServer()
}

func RegisterGameSerivceServer(s grpc.ServiceRegistrar, srv GameSerivceServer) {
	// If the following call panics, it indicates UnimplementedGameSerivceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameSerivce_ServiceDesc, srv)
}

func _GameSerivce_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameSerivceServer).Play(&grpc.GenericServerStream[PlayerAction, ServerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameSerivce_PlayServer = grpc.BidiStreamingServer[PlayerAction, ServerResponse]

// GameSerivce_ServiceDesc is the grpc.ServiceDesc for GameSerivce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameSerivce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battle.GameSerivce",
	HandlerType: (*GameSerivceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Play",
			Handler:       _GameSerivce_Play_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/game.proto",
}
