// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: proto/game.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*PlayerAction_Join
	//	*PlayerAction_Move
	Action        isPlayerAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAction) GetAction() isPlayerAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PlayerAction) GetJoin() string {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Join); ok {
			return x.Join
		}
	}
	return ""
}

func (x *PlayerAction) GetMove() *Move {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Move); ok {
			return x.Move
		}
	}
	return nil
}

type isPlayerAction_Action interface {
	isPlayerAction_Action()
}

type PlayerAction_Join struct {
	Join string `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type PlayerAction_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

func (*PlayerAction_Join) isPlayerAction_Action() {}

func (*PlayerAction_Move) isPlayerAction_Action() {}

type ServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ServerResponse_WaitForSecond
	//	*ServerResponse_GameStart
	//	*ServerResponse_Board
	//	*ServerResponse_GameOver
	Response      isServerResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResponse) GetResponse() isServerResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ServerResponse) GetWaitForSecond() string {
	if x != nil {
		if x, ok := x.Response.(*ServerResponse_WaitForSecond); ok {
			return x.WaitForSecond
		}
	}
	return ""
}

func (x *ServerResponse) GetGameStart() string {
	if x != nil {
		if x, ok := x.Response.(*ServerResponse_GameStart); ok {
			return x.GameStart
		}
	}
	return ""
}

func (x *ServerResponse) GetBoard() *Board {
	if x != nil {
		if x, ok := x.Response.(*ServerResponse_Board); ok {
			return x.Board
		}
	}
	return nil
}

func (x *ServerResponse) GetGameOver() string {
	if x != nil {
		if x, ok := x.Response.(*ServerResponse_GameOver); ok {
			return x.GameOver
		}
	}
	return ""
}

type isServerResponse_Response interface {
	isServerResponse_Response()
}

type ServerResponse_WaitForSecond struct {
	WaitForSecond string `protobuf:"bytes,1,opt,name=waitForSecond,proto3,oneof"`
}

type ServerResponse_GameStart struct {
	GameStart string `protobuf:"bytes,2,opt,name=gameStart,proto3,oneof"`
}

type ServerResponse_Board struct {
	Board *Board `protobuf:"bytes,3,opt,name=board,proto3,oneof"`
}

type ServerResponse_GameOver struct {
	GameOver string `protobuf:"bytes,4,opt,name=gameOver,proto3,oneof"`
}

func (*ServerResponse_WaitForSecond) isServerResponse_Response() {}

func (*ServerResponse_GameStart) isServerResponse_Response() {}

func (*ServerResponse_Board) isServerResponse_Response() {}

func (*ServerResponse_GameOver) isServerResponse_Response() {}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []string               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Turn          string                 `protobuf:"bytes,2,opt,name=turn,proto3" json:"turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *Board) GetRows() []string {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Board) GetTurn() string {
	if x != nil {
		return x.Turn
	}
	return ""
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x06battle\"\"\n" +
	"\x04Move\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"R\n" +
	"\fPlayerAction\x12\x14\n" +
	"\x04join\x18\x01 \x01(\tH\x00R\x04join\x12\"\n" +
	"\x04move\x18\x02 \x01(\v2\f.battle.MoveH\x00R\x04moveB\b\n" +
	"\x06action\"\xa9\x01\n" +
	"\x0eServerResponse\x12&\n" +
	"\rwaitForSecond\x18\x01 \x01(\tH\x00R\rwaitForSecond\x12\x1e\n" +
	"\tgameStart\x18\x02 \x01(\tH\x00R\tgameStart\x12%\n" +
	"\x05board\x18\x03 \x01(\v2\r.battle.BoardH\x00R\x05board\x12\x1c\n" +
	"\bgameOver\x18\x04 \x01(\tH\x00R\bgameOverB\n" +
	"\n" +
	"\bresponse\"/\n" +
	"\x05Board\x12\x12\n" +
	"\x04rows\x18\x01 \x03(\tR\x04rows\x12\x12\n" +
	"\x04turn\x18\x02 \x01(\tR\x04turn2G\n" +
	"\vGameSerivce\x128\n" +
	"\x04Play\x12\x14.battle.PlayerAction\x1a\x16.battle.ServerResponse(\x010\x01B+Z)github.com/Dzetner/tic-tac-toe-grpc/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_game_proto_goTypes = []any{
	(*Move)(nil),           // 0: battle.Move
	(*PlayerAction)(nil),   // 1: battle.PlayerAction
	(*ServerResponse)(nil), // 2: battle.ServerResponse
	(*Board)(nil),          // 3: battle.Board
}
var file_proto_game_proto_depIdxs = []int32{
	0, // 0: battle.PlayerAction.move:type_name -> battle.Move
	3, // 1: battle.ServerResponse.board:type_name -> battle.Board
	1, // 2: battle.GameSerivce.Play:input_type -> battle.PlayerAction
	2, // 3: battle.GameSerivce.Play:output_type -> battle.ServerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[1].OneofWrappers = []any{
		(*PlayerAction_Join)(nil),
		(*PlayerAction_Move)(nil),
	}
	file_proto_game_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerResponse_WaitForSecond)(nil),
		(*ServerResponse_GameStart)(nil),
		(*ServerResponse_Board)(nil),
		(*ServerResponse_GameOver)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
